
services:
  app:
    build: .
    container_name: filmpackager 
    ports:
      - "8080:8080" # Change based on your Go app’s port
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb?sslmode=disable
    depends_on:
      - db
    volumes:
      - .:/app
      - .env:/app/.env
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: go_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

